### ISSUE TITLE
ini kenapa close session mulu

### ISSUE THREAD

**Issue by NugrahaMP** [fdhlgrphy/Crizzy-Bot#3]
![Screenshot_2022-10-08-18-59-25-715_com.termux.jpg](https://user-images.githubusercontent.com/86095279/194704198-a80b5c6e-d95e-4be5-8f52-9d3ae756852a.jpg)

dari tadi close session mulu, gimana ya

**Comment by fdhlgrphy** [comment]
Gpp itu
